In [1]:
import numpy as np
data = [1,2,3,4,5]
n = np.array(data*10)
print(data)
print(n)

[1, 2, 3, 4, 5]
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2
 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [2]:
n.shape

(50,)

In [3]:
n.dtype

dtype('int64')

# 嵌套序列

In [4]:
arr = [[1,2,3,4], [1,2,3,4]]
arr2 = np.array(arr)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]
 [1 2 3 4]]
2
(2, 4)


In [5]:
### np对数据类型的一个判断

In [8]:
# 不好的示范
arr = [['1','2',3,4],[5,6,7,8]]
arr2 = np.array(arr)
print(arr)
print(arr2.dtype) # unicode类型

[['1', '2', 3, 4], [5, 6, 7, 8]]
<U1


In [9]:
arr = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(arr)
print(arr2)
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]]
int64


In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.empty((2,3,4))

array([[[4.65833018e-310, 0.00000000e+000, 6.89894674e-310,
         1.03259720e-321],
        [6.89895000e-310, 4.65833017e-310, 6.89894014e-310,
         6.89894014e-310],
        [6.89894014e-310, 6.89894014e-310, 6.89894014e-310,
         6.89894014e-310]],

       [[6.89894014e-310, 6.89894014e-310, 6.89894014e-310,
         6.89894014e-310],
        [6.89894014e-310, 6.89894014e-310, 6.89894760e-310,
         6.89894014e-310],
        [6.89894014e-310, 6.89894014e-310, 6.89894760e-310,
         6.89894014e-310]]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.array([1.2,1.6,1.8,-2.3,-5.8])

In [17]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr1 + arr2

array([ 6,  8, 10, 12])