In [15]:
from __future__ import print_function
import numpy as np
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
from keras.layers.normalization import BatchNormalization
import matplotlib.pyplot as plt

In [16]:
%matplotlib inline

In [17]:
losses = []

In [18]:
def loadImageFile(fileimage):
    f = open(fileimage, "rb")
    f.read(16)
    pixels = 28*28
    images_arr = []
    while True:
        try:
            img = []
            for j in range(pixels):
                pix = ord(f.read(1))
                img.append(pix/255)
            images_arr.append(img)
        except:
            break
    f.close()
    images_sets = np.array(images_arr)
    return images_sets

In [19]:
def loadLabelFile(filelabel):
    f = open(filelabel, "rb")
    f.read(8)
    labels_arr = []
    while True:
        row = [0 for x in range(10)]
        try:
            label = ord(f.read(1))
            row[label] = 1
            labels_arr.append(row)
        except:
            break
    f.close()
    label_sets = np.array(labels_arr)
    return label_sets

In [20]:
train_images = loadImageFile("./train-images-idx3-ubyte")
train_labels = loadLabelFile("./train-labels-idx1-ubyte")

In [21]:
test_images = loadImageFile("./t10k-images-idx3-ubyte")
test_labels = loadLabelFile("./t10k-labels-idx1-ubyte")

In [22]:
print(train_images)
print(train_labels)
print(test_images)
print(test_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
x_train = train_images.reshape(train_images.shape[0], 28, 28, 1)
x_test = test_images.reshape(test_images.shape[0], 28, 28, 1)
y_train = train_labels
y_test = test_labels

In [24]:
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(28,28,1)))
model.add(Activation('relu'))
BatchNormalization(axis=-1)
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

In [25]:
BatchNormalization(axis=-1)
model.add(Conv2D(64,(3, 3)))
model.add(Activation('relu'))
BatchNormalization(axis=-1)
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
# Fully connected layer

BatchNormalization()
model.add(Dense(512))
model.add(Activation('relu'))
BatchNormalization()
model.add(Dropout(0.2))
model.add(Dense(10))

model.add(Activation('softmax'))

In [26]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adam(),
              metrics=['accuracy'])

In [27]:
model.fit(x_train, y_train,
          batch_size=100,
          epochs=10,
          verbose=2,
          validation_split=0.2)

Epoch 1/10
480/480 - 29s - loss: 0.1765 - accuracy: 0.9448 - val_loss: 0.0484 - val_accuracy: 0.9861
Epoch 2/10
480/480 - 5s - loss: 0.0453 - accuracy: 0.9857 - val_loss: 0.0455 - val_accuracy: 0.9858
Epoch 3/10
480/480 - 4s - loss: 0.0305 - accuracy: 0.9907 - val_loss: 0.0393 - val_accuracy: 0.9885
Epoch 4/10
480/480 - 4s - loss: 0.0215 - accuracy: 0.9929 - val_loss: 0.0356 - val_accuracy: 0.9891
Epoch 5/10
480/480 - 5s - loss: 0.0172 - accuracy: 0.9941 - val_loss: 0.0376 - val_accuracy: 0.9893
Epoch 6/10
480/480 - 6s - loss: 0.0147 - accuracy: 0.9953 - val_loss: 0.0326 - val_accuracy: 0.9908
Epoch 7/10
480/480 - 9s - loss: 0.0126 - accuracy: 0.9961 - val_loss: 0.0340 - val_accuracy: 0.9905
Epoch 8/10
480/480 - 9s - loss: 0.0114 - accuracy: 0.9960 - val_loss: 0.0320 - val_accuracy: 0.9912
Epoch 9/10
480/480 - 9s - loss: 0.0094 - accuracy: 0.9969 - val_loss: 0.0422 - val_accuracy: 0.9906
Epoch 10/10
480/480 - 9s - loss: 0.0078 - accuracy: 0.9975 - val_loss: 0.0473 - val_accuracy: 0.987

In [28]:
score = model.evaluate(x_test, y_test, verbose=1)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

313/313 [==============================] - 5s 15ms/step - loss: 0.0371 - accuracy: 0.9891
Test loss: 0.037148598581552505
Test accuracy: 0.9890999794006348


In [29]:
model.save_weights("weights.h5")

In [30]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)